[versions]
agp = "8.13.2"
digia_ui_compose = "1.0.0-beta.4"
kotlin = "2.0.21"
clevertap = "5.0.0"

[libraries]
clevertap-android-sdk = { group = "com.clevertap.android", name = "clevertap-android-sdk", version.ref = "clevertap" }
digia_ui_compose = { module = "com.github.Digia-Technology-Private-Limited:digia_ui_compose", version.ref = "digia_ui_compose" }


[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }